### ISSUE TITLE
does not work inside worker_thread

### ISSUE THREAD

**Issue by helios1138** [substack/node-mkdirp#148]
I know it's an experimental feature of node, but nonetheless the error I get is this:

```
TypeError: process.umask is not a function
    at sync (/app/node_modules/mkdirp/index.js:64:34)
    at process.save (/app/node_modules/babel-register/lib/cache.js:47:20)
```

**Comment by Sitronik** [comment]
I get this error too:
```javascriptTypeError: process.umask is not a function
    at sync (/Users/denis/Documents/wedobet/wedobet-bk/node_modules/mkdirp/index.js:64:34)
    at save (/Users/denis/Documents/wedobet/wedobet-bk/node_modules/babel-register/lib/cache.js:47:20)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at MessagePort.port.on (internal/worker.js:445:27)
    at MessagePort.emit (events.js:182:13)
    at MessagePort.onmessage (internal/worker.js:66:8)
```

**Comment by Sitronik** [comment]
I get this error too:
```javascript
TypeError: process.umask is not a function
    at sync (/app/node_modules/mkdirp/index.js:64:34))
    at save (/app/node_modules/babel-register/lib/cache.js:47:20)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at MessagePort.port.on (internal/worker.js:445:27)
    at MessagePort.emit (events.js:182:13)
    at MessagePort.onmessage (internal/worker.js:66:8)
```

**Comment by yygutn** [comment]
i have this issue, too

**Comment by yygutn** [comment]
> faced with this issue as well

+1

**Comment by Oroneki** [comment]
+1

**Comment by mikeebowen** [comment]
+1
